# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d166b6dd474bd37a4dac6f4300557345"
application_url = "https://kind-globe-au-apparent.trycloudflare.com"
embedded = true
name = "webdgpu-3d-model-viewer"
handle = "webdgpu-3d-model-viewer"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://kind-globe-au-apparent.trycloudflare.com/auth/callback",
  "https://kind-globe-au-apparent.trycloudflare.com/auth/shopify/callback",
  "https://kind-globe-au-apparent.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "webgpu.myshopify.com"
automatically_update_urls_on_dev = true
