# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d166b6dd474bd37a4dac6f4300557345"
application_url = "https://amino-resolve-commander-breakdown.trycloudflare.com"
embedded = true
name = "webdgpu-3d-model-viewer"
handle = "webdgpu-3d-model-viewer"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_product_listings,read_files,read_themes,write_files,write_themes"

[auth]
redirect_urls = [
  "https://amino-resolve-commander-breakdown.trycloudflare.com/auth/callback",
  "https://amino-resolve-commander-breakdown.trycloudflare.com/auth/shopify/callback",
  "https://amino-resolve-commander-breakdown.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://amino-resolve-commander-breakdown.trycloudflare.com/api/viewer"
subpath = "webgpu-viewer"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "webgpu.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
